version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_DATABASE=Cry_movie
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_DIALECT=mysql
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: Cry_movie
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db-data:
